### ISSUE TITLE
expose all three ports in dev container

### ISSUE THREAD

**Issue by raffaelespazzoli** [quarkiverse/quarkus-openfga-client#15]
currently the dev container expose 8080 which is the http port. But the client uses grpc (8081), is that going to work?
also the playground port (3000) is very useful for troubleshooting.
All three ports should be expose to the host by the dev container.

**Comment by kdubb** [comment]
This client uses HTTP not GRPC; OpenFGA supports both.

**Comment by kdubb** [comment]
Yes, exposing we should be exposing all the ports.

As far as HTTP vs GRCP, HTTP is dramatically simpler to implement. Also, a single 3 item JSON map request and a boolean result is transmitted for the `check` operation; which is what is required to be performant.

I plan on ensuring we are connecting with HTTP/2 (which is also what gRPC uses) and probably leave it there for a while.

**Comment by iocanel** [comment]
@kdubb: I am half way through adding grpc support. The question is should we completely switch or provide both options?

**Comment by kdubb** [comment]
I'm not sure. No reason to maintain something nobody ever uses. Then again, maybe somebody cannot run gRPC and need the HTTP client.
