### ISSUE TITLE
[Feature Request] Ability to load the model from a well known location with devcontainers

### ISSUE THREAD

**Issue by raffaelespazzoli** [quarkiverse/quarkus-openfga-client#8]
it's unclear from the doc how the lcoation property works `quarkus.openfga.devservices.authorization-model.location` : what is the base folder, or is this a classpath.
But it wuld be even better if when using dev services the model was load from a well know path, for example `src/main/resource/openfga-model.json`

**Comment by kdubb** [comment]
Read the docs for `location`. It follows the Flyway model:
```
    /**
     * Location of JSON formatted authorization model file to upload during DevServices initialization.
     * <p>
     * The location can be prefixed with {@code classpath:} or {@code filesystem:} to specify where the file
     * will be read from; if not prefixed, it will be read from the classpath.
     */
```

**Comment by raffaelespazzoli** [comment]
where can I find the docs? So far I only found the git repo readme.

**Comment by kdubb** [comment]
Currently only the configuration objects are defined, and only in code; `OpenFGAConfig` and `OpenFGABuildTimeConfig`.

**Comment by kdubb** [comment]
I've closed this because it's essentially a documentation issue; being that we don't have proper documentation lol
