### ISSUE TITLE
[Feature request] add the ability to add tuples to a model when using dev containers

### ISSUE THREAD

**Issue by raffaelespazzoli** [quarkiverse/quarkus-openfga-client#9]
It would be useful to be able to initialize the model with some tuples (facts) when using the devcontainer.

**Comment by kdubb** [comment]
The configuration properties are `authorizationTuples` or `authorizationTuplesLocation`. The location property follows the same lookup as `authorizationModelLocation`.

**Comment by raffaelespazzoli** [comment]
@kdubb would you be able to make a releases with the latest fixes/enhancements?
